name: "tfsec action"
description: "Runs tfsec and outputs any failures"
author: "owen.rumney@aquasec.com"

inputs:
  working_directory:
    required: false
    description: |
      Directory to run the action on, from the repo root.
      Default is . (root of the repository)
    default: "."
  version:
    required: false
    description: The version of tfsec to use, defaults to latest
    default: latest
  format:
    required: false
    description: the format of the output
    default: default
  additional_args:
    required: false
    description: |
      Space separated args specified here will be added during tfsec execution.
      (eg. --force-all-dirs --verbose)
  soft_fail:
    required: false
    description: If set to `true` the action step won't break the build
  install:
    required: false
    description: If set to `true` the action installs tf-sec
    default: "true"
  run:
    required: false
    description: If set to `true` the action runs tf-sec
    default: "true"
  cache:
    required: false
    description: If set to `true` the action caches tf-sec
    default: "true"
  debug:
    required: false
    description: If set to `true` the action outputs debug
    default: "false"
outputs:
  tfsec-return-code:
    value: ${{ steps.tfsec.outputs.EXIT_CODE }}
    description: "tfsec command exit code"
runs:
  using: composite
  steps:
    - name: Install tfsec
      if: ${{ inputs.install != 'false' }}
      shell: bash
      run: "$GITHUB_ACTION_PATH/src/install.sh"
      env:
        INPUT_DEBUG: ${{inputs.debug}}
        INPUT_CACHE: ${{inputs.cache}}
        INPUT_VERSION: ${{inputs.version}}

    - name: Run tfsec
      if: ${{ inputs.run != 'false' }}
      shell: bash
      id: tfsec
      run: |
        set +e
        tfsec --format="${INPUT_FORMAT}" ${INPUT_SOFT_FAIL:+--soft-fail} ${TFSEC_ARGS_OPTION} "${INPUT_WORKING_DIRECTORY}"
        EXIT_CODE=$?
        echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_OUTPUT
        exit $EXIT_CODE
      env:
        INPUT_FORMAT: ${{inputs.format}}
        INPUT_SOFT_FAIL: ${{inputs.soft_fail}}
        INPUT_WORKING_DIRECTORY: ${{inputs.working_directory}}
        TFSEC_ARGS_OPTION: ${{inputs.additional_args}}

branding:
  icon: "git-pull-request"
  color: "purple"
